export const jobOffers = [
  { 
    id: 128, 
    zone: "Abidjan", 
    category: "esthétique prothésistes ongulaire", 
    title: " Recheche un espace a abobo pour gerance libre ", 
    description:"Je suis une  prothésiste Ongulaire Pro à la recherche d'un Espace à louer dans un salon a abobo ou n'dotré merci",
    location:"abidjan abobo", 
    salary: "a discute",
    whatsapp: "2250778597010", 
    number: "+(225)0545850649", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "23-Juin-2026"
  },
  { 
    id: 127, 
    zone: "Abidjan", 
    category: "Coiffure barber zone  gerance libre avec dortoire ", 
    title: "salon recherche coiffeur pour gerance ", 
    description:"Salon de coiffure à Songon Agban cherche un coiffeur. En GERANCE CONTRÔLÉE Consciencieux, professionnel et respectueux. Avec DORTOIR",
    location: "Abidjan yop", 
    salary: "a discute",
    whatsapp: "2250778597010", 
    number: "+(225)0140470971", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "23-Juin-2026"
  },
  { 
    id: 126, 
    zone: "Abidjan", 
    category: "Barber zone abidjan rivera atoban", 
    title: "recherche d'un Espace à louer", 
    description:"Recheche coofeur barber habitant dans la zone tzxte Salut la famille ! besoin d'un coiffeur respectueux pour un salon Abidjan Atoban 30ème, salaire bien payé avec plaisir... mais le coiffeur qui habite dans le secteur pas de dortoir appelé  pas de dortoire.  ",
    location: "abidjan rivera ", 
    salary: "a discute",
    whatsapp: "2250778597010", 
    number: "+(225)0574207332", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "23-Juin-2026"
  },
  { 
    id: 125, 
    zone: "Abidjan", 
    category: "prothésiste ", 
    title: "recherche d'un Espace à louer", 
    description:"Je suis une  prothésiste Ongulaire Pro à la recherche d'un Espace à louer dans un salon a abobo ou n'dotré merci ",
    location: "Abobo  ou n'dotré", 
    salary: "non précisé",
    whatsapp: "2250778597010", 
    number: "+(225)0545850649", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "23-Juin-2026"
  },
  { 
    id: 124, 
    zone: "Abidjan", 
    category: "Coiffure ", 
    title: "nouveau salon recherche coiffure barber", 
    description:"Un nouveau salon de coiffure moderne ouvre bientôt ses portes à Abobo Sotrapim et recherche un : 💈 COIFFEUR HOMMES EXPÉRIMENTÉ 💈Profil recherché : ✅ Maîtrise des coupes modernes et classiques ✅ Sens de l'accueil et du service client ✅ Sérieux, ponctuel et professionnel ✅ Bonne présentation",
    location: "Abobo Sotrapim", 
    salary: "non précisé",
    whatsapp: "2250778597010", 
    number: "+(225) 07 78 09 74 59 (225) 01 02 17 21 38", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "23-Juin-2026"
  },
  { 
    id: 123, 
    zone: "Abidjan", 
    category: "Coiffure barber zone abidjan akouedo ", 
    title: "recherche coiffeur a Akouedo", 
    description:"Besoin d'un coiffeur a akouedo habitez au alentour sera favorable le salaire commence à partir de 80k en fonction des compétences  appel moi  8566 ou whatsapp",
    location: "Abidjan akouedo ", 
    salary: "80k Fcfa",
    whatsapp: "2250778597010", 
    number: "+225058410", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "23-Juin-2026"
  },
  { 
    id: 122, 
    zone: "Abidjan", 
    category: "🛑Categorire", 
    title: "Recherche coiffeuse talentuese", 
    description:"salaire a discuté pas de dortoire  Nous recherchons une coiffeuse talentueuse, sérieuse et ponctuelle qui sait faire: 👉🏽 Nattes, tresses, twists, tissages, poses perruques et coiffures tendance Un plus pour les soins du visage, pedicure, et gommage du corps Si ça t’intéresse Ecrivez directement sur WhatApp  #coiffeuse #recrutement #salondecoiffure #ANGRE",
    location: "zone abidjan aboboté ", 
    salary: "",
    whatsapp: "2250778597010", 
    number: "+225📱07 59 19 30 59", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "19-Juin-2026"
  },
  { 
    id: 121, 
    zone: "Abidjan", 
    category: "🛑Categorire", 
    title: "Coiffeur cherche  salon a la rivera", 
    description:"Je suis coiffeur a la recherche d'un salon de coiffure je réside a Cocody Riviera Faya mon numéro",
    location: "Abidjan rivera", 
    salary: "non precisé",
    whatsapp: "2250778597010", 
    number: "+2250501026582", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "22-Juin-2026"
  },
  { 
    id: 121, 
    zone: "Abidjan", 
    category: "Coiffure", 
    title: "RECRUTEMENT COIFFEUSE À ANGRÉ Nous recherchons une coiffeuse talentueuse", 
    description:"🛑 RECRUTEMENT COIFFEUSE À ANGRÉ Nous recherchons une coiffeuse talentueuse, sérieuse et ponctuelle qui sait faire:👉🏽 Nattes, tresses, twists, tissages, poses perruques et coiffures tendanceUn plus pour les soins du visage, pedicure, et gommage du corps Angré 7eme tranche  Si ça t’intéresse Ecrivez directement sur WhatApp #coiffeuse #recrutement #salondecoiffure #ANGRE",
    location: "Abidjan Angré 7eme tranche  ", 
    salary: "",
    whatsapp: "2250778597010", 
    number: "+225 📱07 99 36 21 78", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "19-Juin-2026"
  },
  { 
    id: 120, 
    zone: "Abidjan", 
    category: "Coiffure", 
    title: "Recherche coiffeur rivera 2 ", 
    description:"Bonjour besoin d'un coiffeur professionnel a la riviera 2 salaire 100.000f pas de dortoir.  uniquement WhatsApp svp",
    location: "zone abidjan rivera", 
    salary: "100.000 Fcfa",
    whatsapp: "2250778597010", 
    number: "+2250500522820", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "19-Juin-2026"
  },
  { 
    id: 119, 
    zone: "Abidjan", 
    category: "coiffure pas de dortoire salaire", 
    title: " salon abobo recherche coiffeuse polyvalente", 
    description:"Salon a Abobo recrute une coiffeuse professionnelle qui maîtrise très bien les poses perruques et les tresses.salaire 130 mil",
    location: "Abidjan abobo ", 
    salary: "130 .000 F cfa",
    whatsapp: "2250778597010", 
    number: "+225 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "17-Juin-2026"
  },
  { 
    id: 117, 
    zone: "Intérieur ", 
    category: "Coiffure", 
    title: "recherche professionnel polyvalent  pour salon a bassam ", 
    description:"Je recherche une coiffeuse ou un homme qui c’est très bien fait la coiffure pour femmes tout mèche les pause perruque natte toutes les coiffures et une personne qui fait les Onglerie et rajout fossiles aussi tu métriez ton travail vient travailler il y a un dortoir le salon est à Bassam Intéressé WhatsApp ￼",
    location: "intérieur  bassam ", 
    salary: "Salaire non précisé",
    whatsapp: "2250596132058", 
    number: "+225 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "17-Juin-2026"
  },
  { 
    id: 118, 
    zone: "Abidjan ", 
    category: "coiffure gerance libre avec dortoire", 
    title: " coiffeur polyvalent maitrise homme et dame", 
    description:"Je suis Abidjan  je fait Locks coupe homme et femme et aussi collage de peurruque homme pour les cérémonies et je vais fait tout sorte de teinture couleur c’est pour travailler sous contrat intéressé voici mon numéro ",
    location: "Abidjan", 
    salary: "Salaire ou gerance",
    whatsapp: "2250596132058", 
    number: "+2250173096846 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "15-Juin-2026"
  },
  { 
    id: 115, 
    zone: "Intérieur ", 
    category: "estheticienne", 
    title: " estheticienne  masseuses prothésiste ongulaire recherche travail ", 
    description:"Je suis esthéticienne exercent en soins de visage, gommage de corps(clarifiant et éclaircissant),hammam marocain, lipocavition,Madero thérapie, maquilleuse, prothésiste ongulaire ( permanent,gel, résine,poly gel, double capsule, gainage) extension de cils ( classique, hybride,russe et méga volume) je réside à Bouaké. Je cherche un travail avec dortoir, prétention salariale 160.000 f",
    location: "", 
    salary: "160.000 f ou gerance libre",
    whatsapp: "2250596132058", 
    number: "+2250788674006 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "07-Juin-2026"
  },
  { 
    id: 114, 
    zone: "Abidjan ", 
    category: "Coiffure", 
    title: "Salon azito recherche coiffeur pour gerance", 
    description:" Salon de coiffure mixte situé à yopougon Azito totalement équipé cherche des personnes sérieuses pour une gérance libre intéressé ",
    location: "abidjan yop azito ", 
    salary: "Non defini",
    whatsapp: "2250596132058", 
    number: "+2250749905229 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "07-Juin-2026"
  },
  { 
    id: 113, 
    zone: "Abidjan ", 
    category: "Coiffure barber", 
    title: "Recherche d'un salon de coiffure", 
    description:"je suis à la recherche d'un salon de coiffure merci mon contact je suis un coiffeur je cherche un salon de coiffure",
    location: "", 
    salary: "Non defini",
    whatsapp: "2250596132058", 
    number: "+2250556311621 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "07-Juin-2026"
  },
  { 
    id: 112, 
    zone: "Abidjan ", 
    category: "Coiffure barber", 
    title: "recherche coiffeuse dortoire disponible 80.000 a 100.000", 
    description:"Recherche couffeur talentueux a n'dotré texte   Salon de coiffure à  N'DOTRE KOBAKRO  cherche un coiffeur.Consciencieux, professionnel et respectueux. Avec DORTOIR Intéressé appelez-moi",
    location: "Abobo n'dotré.", 
    salary: "salaire non defini dortoire disponible",
    whatsapp: "2250596132058", 
    number: "+2250769396282 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "07-Juin-2026"
  },
  { 
    id: 109, 
    zone: "Intérieur", 
    category: "Coiffure", 
    title: "  recherche coiffeuse dortoire disponible 80.000 a 100.000  ", 
    description: " j'ai besoin d'une coiffeuse à aboiss Tresse et pose perruques, ongle si possible , oui il y a dortoir , 80 mil cme salaire ",
    location: "Qboisso .", 
    salary: "80 000   a 100 000Fcfa",
    whatsapp: "2250596132058", 
    number: "+225 0757502618 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "07-Juin-2026"
  },
  { 
    id: 108, 
    zone: "Abidjan", 
    category: "Coiffure", 
    title: " Coiffeur maîtrisant la coiffure europeen recherche poste a zone 4", 
    description: "coiffeur categorie coiffure zone abidjan bietry zone 4  avec dortoir   salaire gérance libre      professionnel maîtrisant coiffure européens  coloration brushing coupe européenne keratine   experience  recherche salon en gerance libre   zone abidjan zone 4 bietry  marcory Blaise Coiffure: ",
    location: "Situé à angre .", 
    salary: "gérance libre pas de dortoire.",
    whatsapp: "2250596132058", 
    number: "00221774615064 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "07-Juin-2026"
  },
  { 
    id: 110, 
    zone: "Abidjan", 
    category: "Esthétique zone  abidjan Angre", 
    title: "espace onglerie en gerance libre ", 
    description: "Tu es coiffeuse ou prothésiste j’ai un salon de coiffure dame pr toi en gestion libre . Tu es prothésiste j’ai un espace en gérance libre pour toi .  appel vite à ce numéro pour visiter l’endroit .",
    location: "Situé à angre .", 
    salary: "gérance libre pas de dortoire.",
    whatsapp: "2250596132058", 
    number: "+2250104967087 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 107, 
    zone: "Abidjan", 
    category: "Coiffure", 
    title: "", 
    description: "Je suis un coiffeur pro disponible je fait un peu de tout (coupe dame. Coupe homme, tout genre de teinture, locks et les tiges ;voici mon numéro whatsapp",
    location: "", 
    salary: "Discuté",
    whatsapp: "2250596132058", 
    number: "+2250103570172 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 106, 
    zone: "Abidjan", 
    category: "Coiffure", 
    title: "Polyvantent recheche travail.", 
    description: "Je suis un coiffeur pro  disponible je fait un peu de tout (coupe dame. Coupe homme, tout genre de teinture, locks et fabricant de tiges de locks avec cheveux naturel etc...)voici mon numéro",
    location: "", 
    salary: "Discuté",
    whatsapp: "2250596132058", 
    number: "+2250103570172 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },

  { 
    id: 105, 
    zone: "Abidjan", 
    category: "Coiffure", 
    title: "Je suis un coiffeur pro", 
    description: "Je suis un coiffeur pro  disponible je fait un peu de tout (coupe dame. Coupe homme, tout genre de teinture, locks et fabricant de tiges de locks avec cheveux naturel etc...)voici mon numéro whatsapp  en pv je vous en verrai mes coiffures en images.",
    location: "Abidjan", 
    salary: "",
    whatsapp: "2250596132058", 
    number: "+2250103570172 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 104, 
    zone: "", 
    category: "Coiffure", 
    title: " recheche   1 barber et. Une coiffeuse specialiste en natte enfant ", 
    description: "M : Profils recherchés : Coiffeur spécialisé en locks et coiffeuse pour nattes libériennes et plates (avec courtoisie et patience).- Logement : Pas de dortoir.",
    location: "Zone abidjan abatta pas de dortoire ", 
    salary: "Salaire fixe avec objectifs et pourcentages",
    whatsapp: "2250596132058", 
    number: "+2250546000710 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 103, 
    zone: "Intérieur", 
    category: "Barber", 
    title: " dortoire disponible salaire a discuté", 
    description: "besoin d'un coiffeur à Yamoussoukro + dortoir un coiffeur Poli je précise  intéressé Apel",
    location: "Yamoussoukro", 
    salary: "",
    whatsapp: "2250596132058", 
    number: "+2250546202384 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 102, 
    zone: "Abidjan", 
    category: "Coiffure", 
    title: "Libre pour coiffeuse ", 
    description: "Salon gerance texte Tu es coiffeuse ou prothésiste j’ai un salon de coiffure dame pr toi en gestion libre .Tu es prothésiste j’ai un espace en gérance libre pour toi . Situé à angre .  appel vite à ce numéro pour visiter l’endroit .",
    location: "Abidjan angre", 
    salary: "",
    whatsapp: "2250596132058", 
    number: "+220104967087 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 101, 
    zone: "Abidjan", 
    category: "Coiffeur", 
    title: "Coiffeur", 
    description: "Je suis à la recherche d'un salon de coiffure en gérance libre",
    location: "Angre", 
    salary: "GÉRANT LIBRE",
    whatsapp: "2250596132058", 
    number: "+2250757047469 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 98, 
    zone: "Abidjan", 
    category: "Coiffeur", 
    title: "Coiffeur", 
    description: "Tu es coiffeuse ou prothésiste j’ai un salon de coiffure dame pr toi en gestion libre .Tu es prothésiste j’ai un espace en gérance libre pour toi .Situé à angre  appel vite à ce numéro pour visiter l’endroit . ",
    location: "Angre", 
    salary: "GÉRANT LIBRE",
    whatsapp: "2250596132058", 
    number: "☎️+2250104967087 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 92, 
    zone: "Abidjan", 
    category: "Coiffeur", 
    title: "coiffeur recherche travail zone pourboire", 
    description: "SALUT JE SUIS COIFFEUR ET JE SUIS CHERCHE SALON POUR TRAVAILLER DANS LES ENVIRON DE PORT BOUËT, PETIT BASSAM, VRIDY CANAL, VRIDY CITÉ ",
    location: "Abidjan", 
    salary: "GÉRANT LIBRE",
    whatsapp: "2250596132058", 
    number: "+220565139710 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 95, 
    zone: "Abidjan", 
    category: "Coiffeur", 
    title: "recherche une prothésiste ongulaire", 
    description: "Salon à Cocody Angré 22ème recherche une prothésiste angulaire  propose un salaire de *90 000 à 120 000 FCFA et sans dortoir. Votre numéro de contact.",
    location: "Cocody Angré 22ème", 
    salary: "90 000 - 120 000 Fcfa ",
    whatsapp: "2250596132058", 
    number: "+2250778986474 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 94, 
    zone: "Intérieur", 
    category: "Coiffure", 
    title: "Coiffeur professionnel maitrise  (Homme & Locks) - 10 ans d'expérience", 
    description: "Poste en gérance libre avec dortoir_Pr, expert en coiffure homme et locks. Disponible immédiatement pour une collaboration sérieuse ",
    location: "Daoukro", 
    salary: "GÉRANT LIBRE",
    whatsapp: "2250596132058", 
    number: "+2250508836247 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 93, 
    zone: "Intérieur", 
    category: "Coiffure", 
    title: "coiffeur recherche travail zone pourboire", 
    description: "Homme sachant réalisée coiffure homme et dame recherche travail  texte coiffeur resident a jacquville je maitrise coiffure homme et dame. Recherche travail  salaire ou gerance libre",
    location: "Jacquville", 
    salary: "GÉRANT LIBRE",
    whatsapp: "2250596132058", 
    number: "+225 0173603339 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 91, 
    zone: "Abidjan", 
    category: "Coiffeur Barber", 
    title: "coiffeur de nationalite beninoise recherche travail", 
    description: "Je suis coiffeur beninois je recherche travail salaire ou gerance libre abidjan avec dortoire", 
    location: "Abidjan", 
    salary: "salaire ou gérance libre",
    whatsapp: "2250596132058", 
    number: "+229 91 84 49 36: 0191844936", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
 
  { 
    id: 90, 
    zone: "Abidjan", 
    category: "Coiffeur Barber", 
    title: "Recherche Prothésiste ongulaire (spécialiste press nails) ", 
    description: "Logement : Aucun dortoir disponible *Localisation :Abidjan Route de Bingerville, Cité Prestige / Cité SIR  ", 
    location: "Abidjan Route de Bingerville", 
    salary: "100 000 FCFA",
    whatsapp: "2250596132058", 
    number: "+22501 72 33 33 93", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 77, 
    zone: "Abidjan", 
    category: "Barber", 
    title: "Categorie coiffure barber ", 
    description: " Coiffeur recherche salon avec dortoire salaire 140 .000 pu gerance libre", 
    location: "Riviera Mbadon", 
    salary: "140 .000 Fcfa",
    whatsapp: "2250596132058", 
    number: "+225 0502495260/ 0502495260", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 79, 
    zone: "Intérieur", 
    category: "Coiffure", 
    title: "coiffeur recherche  salon avec gérance", 
    description: "gerance libre avec dortoire. Je suis un coiffeur professionnel je suis à la recherche d'un salon de coiffure je suis disponible avec dortoir ", 
    location: "", 
    salary: "",
    whatsapp: "2250596132058", 
    number: "+225 0171633962", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 80, 
    zone: "Intérieur", 
    category: "COIFFEUSE", 
    title: "coiffeur recherche  salon avec gérance", 
    description: "RECRUTEMENT COIFFEUR COIFFEUSE Salon de coiffure MIXTE (FEMME ET HOMME) situé à GRAND-BASSAM recherche un(e) très bon(ne) coiffeur(se) professionnel(le), sérieux(se) et dynamique.🎉 Maîtrise des coiffures hommes et femmes🎁 Bonne présentation et sens de l’accueil🎄 Expérience souhaitée",

    location: "GRAND BASSAM", 
    salary: "",
    whatsapp: "2250596132058", 
    number: "+225 0720208120", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 81, 
    zone: "Intérieur", 
    category: "COIFFEUSE", 
    title: "coiffeur recherche  salon avec gérance", 
    description: "RECRUTEMENT COIFFEUR COIFFEUSE Salon de coiffure MIXTE (FEMME ET HOMME) situé à GRAND-BASSAM recherche un(e) très bon(ne) coiffeur(se) professionnel(le), sérieux(se) et dynamique.🎉 Maîtrise des coiffures hommes et femmes🎁 Bonne présentation et sens de l’accueil🎄 Expérience souhaitée",

    location: "GRAND BASSAM", 
    salary: "",
    whatsapp: "2250596132058", 
    number: "+225 0720208120", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 82, 
    zone: "Abidjan", 
    category: "COIFFEUR", 
    title: "recherche un très bon coiffeur ", 
    description: "RECHERCHE COIFFEUR Salon de coiffure homme situé à Yopougon , sérieux et dynamique.✅ Maîtrise des coiffures hommes.✅ Bonne présentation et sens de l’accueil✅ Expérience souhaitée",
    location: "Yopougon Niangon Nord", 
    salary: "",
    whatsapp: "2250596132058", 
    number: "+225 0709221826", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 83, 
    zone: "Abidjan", 
    category: "Esthétique", 
    title: "une specialiste en pedicure recherche travail ", 
    description: "bonjour svp je suis une pedicuriste à la recherche d'un emploi je suis à port Bouet je maîtrise la pédicure les pose capsules et aussi les pose de main tout permanent 🙏",
    location: "Port Bouet ", 
    salary: "salaire a discuté",
    whatsapp: "2250596132058", 
    number: "+225 0153672848", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 99, 
    zone: "Intérieur", 
    category:"Barber", 
    title: "Coiffeur resident a san pedro recherche travail", 
    description: "Barber resident a san pedro recherche salon pour travail salaire ou gérance libre avec dortoire",
    location: "San-pedro", 
    salary: "salaire ou gérance libre",
    whatsapp: "2250596132058", 
    number: "+225 0556263924", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "29-Mai-2026"
  },
  { 
    id: 84, 
    zone: "Intérieur", 
    category: "Coiffeur", 
    title: "Coiffeur resident a san pedro recherche travail", 
    description: "- Profession : Coiffeur (Homme, Dame, Dreadlocks, S'airé locks) - Type de poste : Gérance libre - Localisation  - Besoin : Avec dortoir",
    location: "San-pedro", 
    salary: "Gérance libre ",
    whatsapp: "2250596132058", 
    number: " +225 05 03 17 36 81 / +225 07 19 85 68 16", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "19-Mai-2026"
  },

  {
    id: 70,
    zone: "Abidjan",
    category: "Gérance libre",
    title: "Recherche un coiffeuse pros",
    description:
      " Besoin d’une coiffeuse professionnelle salaire 100 000f Cocody Faya nouveau Gordon ",
    location: "Abidjan cocody faya  ",
    salary: "100.000 Fcfa",
    whatsapp: "2250596132058",
    number: "+2250140268990",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "27-Mai-2026",
  },
  {
    id: 72,
    zone: "Abidjan",
    category: "COIFFEUSE",
    title: "Recherche un coiffeuse pros",
    description:" BESOIN D'UNE COIFFEUSE PROFESSIONNELLE QUI SAIT BIEN COLER LES PERRUQUES À BINGERVILLE SALAIRE :90.000fr ",
    location: "BINGERVILLE",
    salary: "90.000 fr ",
    whatsapp: "2250596132058",
    number: "+22505 64 41 62 54/07 17 57 48 93",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "27-Mai-2026",
  },
  {
    id: 72,
    zone: "Abidjan",
    category: "Barber",
    title: "Coiffeur recherche  salon",
    description:"La famille c'est urgent un coiffeur dynamique à besoin de travaille à bonoua où bassame avec dortoir le numéro WhatsApp est  merci",
    location: "Bonoua où Bassame ",
    salary: "90.000 fr ",
    whatsapp: "2250596132058",
    number: "+2250142576049",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "27-Mai-2026",
  },
  {
    id: 71,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche un coiffeuse pros",
    description:
      "  j’ai urgemment besoin d’une coiffeuse qui maîtrise les poses perruques et tissage rajout  ",
    location: "Yopougon Azito",
    salary: "a discuté ",
    whatsapp: "2250596132058",
    number: "+2250749905229",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "27-Mai-2026",
  },
  
  {
    id: 69,
    zone: "Abidjan",
    category: "Gérance libre",
    title: "Recherche un coiffeur",
    description:
      "Salut, je cherche un coiffeur pour mon salon à djorobite, gérance libre ",
    location: "Djorobite  ",
    salary: "",
    whatsapp: "2250596132058",
    number: "+2250173699602",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "27-Mai-2026",
  },
  {
    id: 68,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche Coiffeur Homme",
    description:
      "Categorie coiffure  barber  zone abidjan abobo n'dotré sans dortoire salaire a discuter  .📢 Recherche Coiffeur Homme ✂️Je suis à la recherche d’un coiffeur homme résidant dans le secteur d’Abobo N’dotré, précisément vers le terminus Trainou.Merci de me contacter ",
    location: "Abobo n'dotré  ",
    salary: "a discuter",
    whatsapp: "2250596132058",
    number: "+2250788629297",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "27-Mai-2026",
  },
  {
    id: 67,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche  gerance  libre  ",
    description:
      "🚨🚨🚨 Un particulier cède un salon de coiffure avec tout le matériel. 📍 Yopougon 40 Prix de cession 💰 900 000 F CFA, y compris : 3 mois de cautio 2 mois d’avance Loyer : 50 000 F CF 📞 01 53 67 29 59",
    location: "Yopougon ",
    salary: "",
    whatsapp: "2250596132058",
    number: "",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "27-Mai-2026",
  },
  {
    id: 64,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Recherche coiffeuse  ",
    description:
      " Categorie coiffure Zone abidjan angre chateau.  a 100.000 pas de dortoire   recherche specialiste en dreadlock  texte. Salon situé a angre chateau recherche coiffeuse spécialiste en dread ",
    location: "Angré chateau ",
    salary: "100.000  Fcfa",
    whatsapp: "2250596132058",
    number: "",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "27-Mai-2026",
  },
  {
    id: 70,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Recherche coiffeuse dortoire disponible ",
    description:
      " Categorie coiffure zone abidjan. Avec dortoir salaire a discuter.  texte  BESOIN D'UNE AIDE COIFFEUSE QUI SAIT TRESSÉ, FAIRE LES MARCOUSSI DANS UN SALON À M'BADON AVEC DORTOIR SALAIRE À DISCUTER SELON TA COMPÉTENCE ",
    location: "M'BADON ",
    salary: "",
    whatsapp: "2250596132058",
    number: "+225  05 64 41 62 54/07 17 57 48 93",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "15-Mai-2026",
  },
  {
    id: 68,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Recherche coiffeur",
    description:
      " Bonjour je suis à la recherche d’un coiffeur au nouveau Cartier Yopougon voilà mon numéro  urgen",
    location: "Yopougon",
    salary: "",
    whatsapp: "2250596132058",
    number: "+2250779940765",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "15-Mai-2026",
  },
  
  {
    id: 65,
    zone: "Intérieur",
    category: "Coiffeur",
    title: "Recherche coiffeur",
    description:
      " Categorie coiffure zone Intérieur bouake pas de dortoire  salaire a discuté  texte Urgent🚨 besoin d'un coiffeur à bouaké quartier ahougnansou ",
    location: "bouaké quartier ahougnansou",
    salary: "",
    whatsapp: "2250596132058",
    number: "+2250152394723",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "15-Mai-2026",
  },
  {
    id: 63,
    zone: "Abidjan",
    category: "Esthétique",
    title: "Recherch estheticienne",
    description:
      " esthétique zone abidjan djorobite pas de dortoir   .  salon salaire 80.000 situé a djorobité recherche estheticienne pros en ongle ",
    location: "Yopougon",
    salary: "80.000",
    whatsapp: "2250596132058",
    number: " +225 0749677984",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "15-Mai-2026",
  },
  {
    id: 62,
    zone: "Abidjan",
    category: "Coiffeuse",
    title: "Recherche coiffeur",
    description:
      " Profil ( coiffeuse) Compétences ( natte plate, Marcoussis, tissage, chion ,posé perruque) Ville ( jacqville)  Salaire fixe 70 mil a 80 mil  Avec dortoir  ",
    location: "Yopougon",
    salary: "70 000 Fcfa à 80 000 Fcfa",
    whatsapp: "2250596132058",
    number: "+2250101030250",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "15-Mai-2026",
  },
  {
    id: 61,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Salon à Treichville cherche coiffeur",
    description:
      " Salon à Treichville cherche coiffeur. Dans la Zone : Treichville / Marcory Possibilité de travailler demain matin",
    location: "Treichville / Marcory",
    salary: "discuter",
    whatsapp: "2250596132058",
    number: "+22507 08 83 10 02",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "15-Mai-2026",
  },
  {
    id: 59,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Recherche coiffeur",
    description:
      " Besoin coiffeur à  koumassi adjawui avec dortoir possible",
    location: "Koumassi adjawi ",
    salary: "",
    whatsapp: "2250596132058",
    number: "+2250173409174",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "15-Mai-2026",
  },
  {
    id: 1,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Recherche gerance libre adjame",
    description:
      "Coiffeuse sanchant faire la Coiffure onglerie et maquillage recherche gerance libre adjame ou environ contacrt",
    location: "Abidjan",
    salary: "100.000 FCFA",
    whatsapp: "2250596132058",
    number: "+0768515338",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "15-Mai-2026",
  },

  {
    id: 2,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Cherche travail Coiffure homme",
    description:
      "Categorie coiffure. Zone abidjan avec dortoire coiffeur pros recherche travail texte Coiffure homme, dame,dread locks, curly.",
    location: "Abidjan",
    salary: "100.000 FCFA",
    whatsapp: "2250596132058",
    number: "+2250140432710",
    likes: 12,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 2,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Cherche Coiffure onglerie et maquillage",
    description:
      "Tu es une coiffeuse tu recherche sous location ou gerance dans la zone d'adjame ou environ.",
    location: "Abidjan",
    salary: "",
    whatsapp: "2250596132058",
    number: "+2250768515338",
    likes: 804,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "17-Mai-2026",
  },

  {
    id: 3,
    zone: "Abidjan",
    category: "COIFFEUR",
    title:
      "recherchons un COIFFEUR PROFESSIONNEL expérimenté pour rejoindre notre nouveau salon moderne",
    description:
      "RECRUTEMENT COIFFEUR PROFESSIONNEL Salon de coiffure homme situé à TREICHVILLE Nous recherchons un COIFFEUR PROFESSIONNEL expérimenté pour rejoindre notre nouveau salon moderne. ✅ PROFIL RECHERCHÉ : - Minimum 2-3 ans d'expérience - Maîtrise des coupes modernes et tendances - Rapidité et qualité du travail- Bon contact avec la clientèle - Présentation soignée et professionnelle 💰 RÉMUNÉRATION ATTRACTIVE : - Salaire fixe + pourcentage (à discuter)  🎁 CE QUE NOUS OFFRONS   - Local moderne et bien équip  - Matériel professionnel fourn  - Excellent emplacement à Treichvill  - Ambiance de travail agréabl  - Possibilité d'évolutionDÉBUT : Immédiat ntéressé(e) ? Contactez-nous dès maintenant !  APPELEZ OU WHATSAPP :   Merci de contacter uniquement si vous habitez à proximité et si vous avez l'expérience requise #Recrutement #CoiffeurAbidjan #Treichville #Marcory #EmploiCotedIvoire #Barbier",
    location: "Abidjan",
    salary: "... FCFA",
    whatsapp: "2250596132058",
    number: "+2250708831002",
    likes: 12,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 4,
    zone: "Abidjan",
    category: "coiffeuse",
    title:
      "Recherche une coiffeuse et celle qui veulent se faire former dans le domaine de la coiffure",
    description:
      "Bonjour je recherche une coiffeuse et celle qui veulent se faire former dans le domaine de la coiffure nous sommes à bingerville précisément dans la zone de ENP",
    location: "Bingerville",
    salary: "... FCFA",
    whatsapp: "2250596132058",
    number: "+2250594478116",
    likes: 102,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 5,
    zone: "Intérieur",
    category: "prothésiste",
    title: "Recherche prothésiste ongulaire  ",
    description:
      "Besoin d’une bonne prothésiste ongulaire à l’intérieur  whatsapp",
    location: "Intérieur",
    salary: "... FCFA",
    whatsapp: "2250596132058",
    number: "+2250506061014",
    likes: 102,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "19-Mai-2026",
  },
  {
    id: 6,
    zone: "Abidjan",
    category: "prothésiste",
    title: "Recherche prothésiste ongulaire  ",
    description:
      "J’ai besoin d’une coiffeuse qui maitrise bien les poses Et une prothésiste ongulaire qui maîtrise toutes les techniques, 90mil ",
    location: "Yopougon",
    salary: "90 000 FCFA",
    whatsapp: "2250596132058",
    number: "+2250778463356",
    likes: 102,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "09-Mai-2026",
  },

  {
    id: 7,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Salon recherche coiffeur propre",
    description:
      "Bonjour institut de beauté situé à la Riviera 2 recherche un coiffeur professionnel avec une bonne hygiène.",
    location: "La Riviera 2",
    salary: "Salaire à discuter",
    whatsapp: "2250596132058",
    number: "+2250140432710",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },

  {
    id: 8,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Salon gerance libre",
    description: "Salon en gerance libre à Bingerville.",
    location: "Bingerville",
    salary: "Salaire à discuter",
    whatsapp: "2250596132058",
    number: "+2250799651489",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },

  {
    id: 9,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Salon recherche coiffeuse polyvalente",
    description:
      "Salon situé à Cocody Angré 8ème tranche recherche une coiffeuse polyvalente.",
    location: "Cocody",
    salary: "80.000 - 120.000 FCFA",
    whatsapp: "2250596132058",
    number: "+225050470326",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 10,
    zone: "Abidjan",
    category: "Esthetique",
    title: "Esthéticienne recherche travail",
    description: "Recherche d'emploi pour prothésiste ongulaire à Port-Bouët.",
    location: "Port-Bouët",
    salary: "150.000 FCFA",
    whatsapp: "2250596132058",
    number: "+2250596560063",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },

  {
    id: 11,
    zone: "Abidjan",
    category: "Esthetique",
    title: "Recherche esthéticienne professionnelle",
    description: "Besoin d'une esthéticienne professionnelle à Cocody Mermoz.",
    location: "Cocody Mermoz",
    salary: "150.000 FCFA",
    whatsapp: "2250596132058",
    number: "+2250798996373",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },

  {
    id: 12,
    zone: "Intérieur",
    category: "Esthetique",
    title: "Recherche prothésiste ongulaire",
    description: "Recrutement d’un prothésiste ongulaire à Bouaké.",
    location: "Bouaké",
    salary: "",
    whatsapp: "2250596132058",
    number: "0554522544 / 0102239508",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  //

  {
    id: 13,
    zone: "Abidjan",
    category: "Formation",
    title: "Recherche apprenties",
    description:
      "Recherche de 3 apprenties en onglerie avec ou sans expérience.",
    location: "Bouaké",
    salary: "50.000 FCFA",
    whatsapp: "2250596132058",
    number: "+2250171793208",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },

  {
    id: 14,
    zone: "Abidjan",
    category: "Formation",
    title: "Coiffeur recherche formation",
    description:
      "Jeune passionné recherche formation en coiffure homme et dreadlocks.",
    location: "Yopougon",
    salary: "",
    whatsapp: "2250596132058",
    number: "+2250777533101",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },

  {
    id: 15,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Recherche coiffeur propre",
    description: "Gerance  sans  dortoire  salon de coiffure situé a adjame ",
    location: "Adjame",
    salary: "",
    whatsapp: "2250596132058",
    number: "+225 08 41 98 19",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "17-Mai-2026",
  },
  {
    id: 16,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Recherche coiffeur",
    description:
      "Gerance libre bouaké recherche coiffeur  barber dortoire disponible",
    location: "Abidjan",
    salary: "",
    whatsapp: "2250596132058",
    number: "+2250757451711",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },
  {
    id: 17,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Recherche un coiffeur ",
    description:
      "Zone  Abidjan songon Categorie coiffure Titre. Recherche un coiffeur Le texte Salon de coiffure à Songon Agban cherche un coiffeur.Consciencieux, professionnel et respectueux. Avec DORTOIR Salaire a discuter ",
    location: "Abidjan Agban",
    salary: "",
    whatsapp: "2250596132058",
    number: "+2250140470971",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },
  {
    id: 18,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Ala recherche d'une coiffeuse professionnelle",
    description:
      "Je  suis a la recherche d'une coiffeuse professionnelle pour rejoindre mon équipe à yopougon millionnaire critères recherchés:- courtoise, acceuillante &professionnelle  - maîtriser la pose perruque( lace,  frontal, closures) - les tresses tendances ( nattes braids)- les tissages - les soins de cheveux",
    location: "Yopougon",
    salary: "Admin",
    whatsapp: "2250596132058",
    number: "+225 0545000811",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 19,
    zone: "Intérieur",
    category: "Coiffeur",
    title: "Recherche un  coiffeur expérimenté ",
    description:
      "Urgent !!!Besoin d’un coiffeur expérimenté pour la gestion d’un salon de coiffure.Salaire de base de 40 000 fr  à 50 000 fr ou Gérance libre .Possibilité d’hébergement Lieu : Bouake précisément dans la localité de Tieningboue",
    location: "Tieningboue",
    salary: "40 000F  à 50 000F",
    whatsapp: "2250596132058",
    number: "0502211966 / 0757451711",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "18-Mai-2026",
  },

  //

  {
    id: 20,
    zone: "Abidjan",
    category: "Recherche travail",
    title: "A la recherche d'un travail ",
    description:
      "Je viens de finir ma formation d'onglerie je cherche un coin où faire un stage pour bien me perfectionner",
    location: "Abobo belle ville",
    salary: "40 000F  à 50 000F",
    whatsapp: "2250596132058",
    number: "+225 0769538828",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "16-Mai-2026",
  },
  {
    id: 21,
    zone: "Intérieur",
    category: "Esthéticien",
    title: "Recherche travail",
    description:
      "Esthéticien homme sachant faire les ongles gel faux cil pose perruque recherche travail a bouaké ou ailleurs avec dortoire salaire ou gerance libre  de 150.000 a 250000",
    location: "Bouaké",
    salary: "150.000 Fcfa - 250000 Fcfa",
    whatsapp: "2250596132058",
    number: "+225 0586959610",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "02-Mai-2026",
  },
  {
    id: 21,
    zone: "Intérieur",
    category: "Coiffure",
    title: "Recherche coiffeur barber ",
    description:
      "Salon de coiffure situé a agboville recherche coiffeur barber. Salaire a discuter dortoire disponible",
    location: "Agboville",
    salary: "....",
    whatsapp: "2250596132058",
    number: "+225 0554115587",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "06-Mai-2026",
  },

  {
    id: 22,
    zone: "Intérieur",
    category: "Coiffeuse",
    title: "Recherche d'une coiffeuse professionnels ",
    description:
      "urgent 🚨je suis à la recherche d'une coiffeuse professionnels pour au solon VIP a bouaké 50000 dortoire disponible Posé peruq place faut ongles tresse gomage ect..",
    location: "bouaké",
    salary: "50 000 Fcfa",
    whatsapp: "2250596132058",
    number: "0152394723 ",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "09-Mai-2026",
  },

  {
    id: 23,
    zone: "Abidjan",
    category: "Prothésiste",
    title: "Offre de formation yopougon",
    description:
      "Tu as envie de devenir une prothésiste professionnelle Eden Éden institut beauty Est la pour toi Viens recevoir une formation en onglerie make-up et la pose perruque de qualité+un emploi garantie dans les Spa et institut Dans la commune de ton choix Éden institut te rend autonome par son programme de qualité si tu souhaites t'installer à ton propre compte ",
    location: "Yopougon",
    salary: "Voir admin",
    whatsapp: "2250596132058",
    number: " 0103036116 ",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "08-Mai-2026",
  },

  {
    id: 24,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Cherche travail salon de coiffure pour être apprenti",
    description:
      "Bonjour à tous je suis un jeune homme qui cherche salon de coiffure pour être apprenti. Je suis vraiment passionné par le métier, j'aimerais apprendre au près d'un coiffeur et travaillé avec lui par la suite",
    location: "Yopougon",
    salary: "...",
    whatsapp: "2250596132058",
    number: "0777533101 ",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 25,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche aide coiffeuse",
    description:
      "Bonjour besoin urgement d'une aide coiffeuse et d'une coiffeuse à cocody non loin de la RTI",
    location: "COcody",
    salary: "Voir admin",
    whatsapp: "2250596132058",
    number: "0103269672",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 26,
    zone: "Intérieur",
    category: "Cherche salon de coiffure pour travail avec dortoire",
    title: "Cherche  travail",
    description:
      "Coiffeur  barber resident a Yamoussokro. Recherche salon de coiffure pour travail avec dortoire. Salaire ou gerance libre",
    location: "Yamoussokro",
    salary: "Salaire ou gerance libre",
    whatsapp: "2250596132058",
    number: "+2250555432860",
    likes: 12,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 27,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Cherche  travail",
    description:
      "Coiffure homme et  locks Je suis Abidjan bingerville J'habite aussi à Gonzague",
    location: "Bingerville Gonzague",
    salary: "...",
    whatsapp: "2250596132058",
    number: "+2250566569181",
    likes: 100,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 28,
    zone: "Intérieur",
    category: "Coiffure",
    title: "Recherche 3 coiffeur 3 barber a yakasse attobrou",
    description:
      "Recherche 3 coiffeur3 barber  a yakasse attobrou competence maitrise du dégrader taper contour dread teinture de couleur. Loyer disponible  salaite 50/50",
    location: "Abata",
    salary: "salaite 50/50",
    whatsapp: "2250596132058",
    number: "+225 0555027936",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "17-Mai-2026",
  },
  {
    id: 29,
    zone: "Abidjan",
    category: "Coiffeuses",
    title: "Ccherche travail",
    description: "Je suis une coiffeuses professionnel En tresses à  Abata",
    location: "Abata",
    salary: "150 000 FCFA",
    whatsapp: "2250596132058",
    number: "+225 0507890767",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },

  {
    id: 30,
    zone: "Abidjan",
    category: "Tresses",
    title: "Cherche travail",
    description:
      "Pas de dortoir, zone de prédilection Abobo belle ville, Abobo baoulé, abobo biabou, Paris village et Angré château limite.",
    location: "Abobo belle ville,",
    salary: "",
    whatsapp: "2250596132058",
    number: "+2250566569181",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },

  //

  {
    id: 31,
    zone: "Abidjan",
    category: "Coiffeuse",
    title: "recherche coiffeuse",
    description:
      "Abata Tout mèches,pose perruque, natte, pedicure.. Salaire  mille",
    location: "Abatta  ",
    salary: "100 000 FCFA",
    whatsapp: "2250596132058",
    number: "+2250757275034",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },
  {
    id: 32,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche une fille  pour soin  de visage, pas de dortoir",
    description:
      "J'ai besoin d'une fille pour faire pédicure manucure et soins de visage pas de dortoir. C'est un salon pour homme",
    location: "Treichville ",
    salary: "~ 80 000 FCFA",
    whatsapp: "2250596132058",
    number: "+225 0747939892:",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },

  {
    id: 33,
    zone: "Abidjan",
    category: "Coiffeuse",
    title: "Cherche travail ",
    description:
      "Coiffeuse polyvalente pose perruque .tresse natte tissage soins de visage manucure   resident a ABOBO DOKUI recherche emploi     dans les environs salaire ",
    location: "ABOBO DOKUI ",
    salary: "~ 130.000 FCFA",
    whatsapp: "2250596132058",
    number: "+225 0545488441",
    likes: 104,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },

  {
    id: 34,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Particulier Gestion LIBRE   Sans  DORTOIR.",
    description:
      "chercher un coiffeur spécialisé en coiffure Mixte où coiffure homme Dans la commune ABOBO anokoi",
    location: "ABOBO ",
    salary: "À débattre",
    whatsapp: "2250596132058",
    number: "+2250100341904",
    likes: 34,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },

  {
    id: 35,
    zone: "Intérieur",
    category: "Coiffure",
    title: "Recherche un Coiffeur.",
    description:
      "Besoins de COIFFEUR - SALAIRE VIP. VILLE DE KORHOGO Gestion LIBRE DORTOIR DISPONIBLE ",
    location: "KORHOGO ",
    salary: "À discuter",
    whatsapp: "2250596132058",
    likes: 34,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },

  {
    id: 36,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche Coiffeur",
    description:
      "Bonjour je cherche un coiffeur pour mon salon situé à gonzaque Pas de dortoir",
    location: "Abidjan ",
    salary: "À débattre",
    whatsapp: "2250596132058",
    likes: 12,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },

  {
    id: 37,
    zone: "Intérieur",
    category: "Esthéticienne",
    title: "Recherche une Esthéticienne",
    description:
      "Recherche une Esthéticienne polyvalente sur Bassam Qui maîtrise le soin de visage, gommage de corps, massage, pédicure manucure et onglerie. Salaire a discuter. NB pas de dortoire",
    location: "Bassam",
    salary: "À débattre",
    whatsapp: "2250596132058",
    number: "2250100134270",
    likes: 109,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },

  {
    id: 38,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche un Coiffure ",
    description:
      "Besoin urgent de Coiffure assidu et patient qui habite a Yopougon Maroc ou aux alentours.",
    location: "Yopougon Maroc",
    salary: "À débattre",
    whatsapp: "2250596132058",
    number: "+22505 96 65 98 58",
    likes: 12,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: false,

    date: "14-Mai-2026",
  },

  {
    id: 39,
    zone: "Abidjan",
    category: "Prothésie",
    title: "Recherche Prothésiste Ongulaire",
    description:
      "Je cherche une prothésiste pour emploi immédiat au nouveau CHU.",
    location: "Angré CHU",
    salary: "À négocier",
    whatsapp: "2250700508392",
    number: "+22507 79 76 26 79",
    likes: 12,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,

    date: "05-Mai-2026",
  },

  {
    id: 40,
    zone: "Abidjan",
    category: "Esthétique",
    title: "Recherche Technicienne de Cils",
    description:
      "Recherche technicienne de cils urgent pour un salon de beauté.",
    location: "Cocody",
    salary: "À négocier",
    whatsapp: "2250799665342",
    number: "+22507 99 665 342",
    likes: 18,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    date: "20-Mai-2026",
  },

  {
    id: 41,
    zone: "Abidjan",
    category: "Prothésie",
    title: "Cherche travail",
    description:
      "Jeune dame polyvalente cherche un emploi. maîtrisant la prothésie ongulaire, les cils et les sourcils.",
    location: "Angré",
    salary: "À négocier",
    whatsapp: "2250777344290",
    number: "+2250777344290",
    likes: 25,
    isUrgent: false,
    isFavorite: true,
    hasDortoir: false,
    isPremium: false,
    date: "11-Mai-2026",
  },

  {
    id: 42,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche Coiffeuse et Aide Coiffeuse",
    description:
      "Recherche une coiffeuse et une aide coiffeuse maîtrisant les tresses et les nattes.",
    location: "Angré CHU",
    salary: "À négocier",
    whatsapp: "2250779762679",
    number: "+2250777344290",
    likes: 16,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    date: "20-Mai-2026",
  },

  {
    id: 43,
    zone: "Abidjan",
    category: "Recherche travail",
    title: "Coiffeur Professionnel  Recherche travail ",
    description: "Coiffeur professionnel recherche un salon avec dortoir.",
    location: "Port-Bouët",
    salary: "À négocier",
    whatsapp: "2250507564428",
    number: "2250507564428",
    likes: 22,
    isUrgent: false,
    isFavorite: true,
    hasDortoir: true,
    isPremium: false,
    date: "21-Mai-2026",
  },

  {
    id: 44,
    zone: "Abidjan",
    category: "Vente / Coiffure",
    title: "Recherche Travail ",
    description:
      "Recherche du travail dans la vente en magasin ou dans un salon de coiffure.",
    location: "Abidjan",
    salary: "À négocier",
    whatsapp: "2250787321090",
    numer: "+2250787321090",
    likes: 14,
    isUrgent: false,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    date: "10-Mai-2026",
  },

  {
    id: 45,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche Coiffeuse et Coiffeur",
    description: "Recherche une coiffeuse et un coiffeur pour un salon.",
    location: "Yopougon Académie",
    salary: "À négocier",
    whatsapp: "2250142517776",
    number: "+2250142517776",
    likes: 20,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    date: "10-Mai-2026",
  },
  {
    id: 46,
    zone: "Abidjan",
    category: "Esthétique",
    title: "Recherche Pédicuriste & Capsules",
    description: "Spécialiste pose capsules et vernis permanent sur pieds.",
    location: "Angré 8ème tranche",
    salary: "90.000 FCFA",
    whatsapp: "2250596132058",
    number: "+22507 78 88 43 99",
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: false,
    date: "2024-05-03",
  },
  {
    id: 47,
    zone: "Abidjan",
    category: "prothésiste",
    title: "Recherche Multi-postes Faya Cité SIR",
    description:
      "#Besoin d'une apprenti qui sait faire pédicure et mettre les ongles et le vernis : 50mill  #Une prothésiste Ongulaire : 70k  #une coiffeuse ou un coiffeur professionnel : 80k #Lieu : Faya Cité SIR ",
    location: "Faya Cité SIR",
    salary: "50.000 - 80.000 FCFA",
    whatsapp: "2250596132058",
    number: "+2250101747343",
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: false,
    date: "2024-05-04",
  },

  {
    id: 48,
    zone: "Abidjan",
    category: "Coiffeuse",
    title: "Recherche Coiffeuse Perruques & Tresses",
    description:
      "J’ai besoin d’ une coiffeuse qui maitrise bien les poses perruques et tresses pour mon salon à yopougon 90mil ",
    location: "Yopougon",
    salary: "90.000 FCFA",
    whatsapp: "2250596132058",
    number: "+2250778463357",
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: false,
    date: "2024-05-05",
  },

  {
    id: 49,
    zone: "Abidjan",
    category: "Coiffure/Coiffeuse",
    title: "Coiffeur(se) Professionnel(le) Perruques",
    description:
      "Besoin urgent d'une coiffeuse ou d'un coiffeur professionnel maîtrisant les poses de perruques.",
    location: "Bingerville",
    salary: "150.000 FCFA",
    whatsapp: "2250710752338",
    number: "+2250710752338",
    likes: 47,
    isUrgent: true,
    isFavorite: true,
    hasDortoir: false,
    isPremium: true,
    date: "10-Mai-2026",
  },

    {
    id: 50,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche Coiffeur ",
    description:
      "Coiffeur professionnel disponible cherche un barber avec possibilité de dortoir.",
    location: "Abidjan",
    salary: "À négocier",
    whatsapp: "2250505800053",
    number: "+2250505800053",
    likes: 28,
    isUrgent: false,
    isFavorite: false,
    hasDortoir: true,
    isPremium: false,
    date: "10-Mai-2026",
  },

  {
    id: 51,
    zone: "Abidjan",
    category: "Coiffeuse",
    title: "Coiffeuse Recherche Travail avec Logement",
    description:
      "Je suis une coiffeuse et je recherche du travail dans un salon avec logement.",
    location: "Abidjan",
    salary: "À négocier",
    whatsapp: "2250150962273",
    number: "+2250150962273",
    likes: 19,
    isUrgent: false,
    isFavorite: true,
    hasDortoir: true,
    isPremium: false,
    date: "10-Mai-2026",
  },

   {
    id: 52,
    zone: "Abidjan",
    category: "Prothésie",
    title: "Cherche travail",
    description:
      "Prothésiste en fin de formation disponible uniquement dans la zone de Angré.",
    location: "Angré",
    salary: "À négocier",
    whatsapp: "2250715416616",
    number: "+2250715416616 ",
    likes: 15,
    isUrgent: false,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    date: "10-Mai-2026",
  },

  {
    id: 53,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche Coiffeuse et Prothésiste Ongulaire",
    description:
      "Recherche une coiffeuse et une prothésiste ongulaire pour un salon sérieux.",
    location: "Yopougon Maroc",
    salary: "À négocier",
    whatsapp: "2250779161504",
    likes: 31,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: true,
    date: "10-Mai-2026",
  },

  { 
    id: 54, 
    zone: "Intérieur", 
    category: "Coiffeuse", 
    title: "Coiffeuse à Bassam", 
    description: "Besoin d'une coiffeuse à Bassam avec dortoir disponible immédiatement. Salaire : 60.000f Heure : 9h a 20h 30 ", 
    location: "Grand-Bassam", 
    salary: "60.000 FCFA",
    whatsapp: "2250596132058", 
    number: "+22505 44 63 91 54", 
    likes: 28,
    isUrgent: false,
    isFavorite: true,
    hasDortoir: true,
    isPremium: false,
    date: "2024-05-14"
  },
   { 
    id: 55, 
    zone: "Abidjan", 
    category: "Esthétique", 
    title: "Recherche Expert Spa & Extensions", 
    description: "Soins corps/visage et extensions de cils (Russe/Hybride).", 
    location: "Riviera Mbadon", 
    salary: "200.000 - 250.000 FCFA",
    whatsapp: "2250596132058", 
    number: "22507 67 95 55 55", 
    likes: 105, // Mis à jour à au moins 12
    isUrgent: false,
    isFavorite: true, 
    hasDortoir: false,
    isPremium: true,
    date: "19-Mai-2026"
  },

   
  { 
    id: 56, 
    zone: "Abidjan", 
    category: "Coiffure", 
    title: "Recherche Coiffeuse experte en poses", 
    description: "Besoin d'une coiffeuse à abatta qui maîtrise surtout les pose perruque. Heure : 9h a 20h 30.", 
    location: "Abatta", 
    salary: "70.000 FCFA",
    whatsapp: "2250596132058", 
    number: "+22505 44 63 91 54", 
    likes: 12,
    isUrgent: false,
    hasDortoir: false,
        isFavorite: true, 

    isPremium: false,
    date: "2024-05-13"
  },

  { 
    id: 57, 
    zone: "Abidjan", 
    category: "Esthétique", 
    title: "Recherche Prothésiste Ongulaire Pro", 
    description: "besoin de deux prothésiste ongulaire urgemment dans la zone d’abobo baoulé, salaire de départ 70k à négocier", 
    location: "Abobo Baoulé", 
    salary: "70.000 FCFA",
    whatsapp: "2250596132058", 
    number: "+2250153488797", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: false,
    date: "2024-05-06"
  },
  { 
    id: 58, 
    zone: "Abidjan", 
    category: "Esthétique", 
    title: "Expert Spa & Extensions", 
    description: "Soins corps/visage et extensions de cils (Russe/Hybride).", 
    location: "Riviera Mbadon", 
    salary: "200.000 - 250.000 FCFA",
    whatsapp: "2250596132058", 
    number: "+22507 67 95 55 55 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "19-Mai-2026"
  },
  
];

export const testimonials = [
  {
    id: 1,
    name: "Awa Koné",
    role: "Coiffeuse Professionnelle",
    content: "Grâce à Goorco, j'ai trouvé un salon à Angré en moins de 48h. Le contact via WhatsApp est ultra rapide !",
    rating: 5,
    avatar: "/esthe1.jpeg"
  },
  {
    id: 2,
    name: "Marc Koffi",
    role: "Gérant de Salon",
    content: "Recruter du personnel qualifié était un calvaire. Avec cette plateforme, j'ai accès aux meilleurs profils de la ville.",
    rating: 5,
    avatar: "/esth2.jpg"
  },
  {
    id: 3,
    name: "Sery Dorcas",
    role: "Esthéticienne",
    content: "La section 'Dortoir disponible' m'a vraiment aidée car je venais de l'intérieur du pays. Je recommande !",
    rating: 4,
    avatar: "/esth3.jpg"
  },

];





