


export const jobOffers = [
  {
    id: 1,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Recherche gerance libre adjame",
    description:
      "Coiffeuse sanchant faire la Coiffure onglerie et maquillage recherche gerance libre adjame ou environ contacrt",
    location: "Abidjan",
    salary: "100.000 FCFA",
    whatsapp: "2250596132058",
    number: "+0768515338",
    likes: 10,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "15-Mai-2026",
  },

  {
    id: 2,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Cherche travail Coiffure homme",
    description:
      "Categorie coiffure. Zone abidjan avec dortoire coiffeur pros recherche travail texte Coiffure homme, dame,dread locks, curly.",
    location: "Abidjan",
    salary: "100.000 FCFA",
    whatsapp: "2250596132058",
    number: "+2250140432710",
    likes: 12,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 2,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Cherche Coiffure onglerie et maquillage",
    description:
      "Tu es une coiffeuse tu recherche sous location ou gerance dans la zone d'adjame ou environ.",
    location: "Abidjan",
    salary: "",
    whatsapp: "2250596132058",
    number: "+2250768515338",
    likes: 804,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "17-Mai-2026",
  },

  {
    id: 3,
    zone: "Abidjan",
    category: "COIFFEUR",
    title:
      "recherchons un COIFFEUR PROFESSIONNEL expérimenté pour rejoindre notre nouveau salon moderne",
    description:
      "RECRUTEMENT COIFFEUR PROFESSIONNEL Salon de coiffure homme situé à TREICHVILLE Nous recherchons un COIFFEUR PROFESSIONNEL expérimenté pour rejoindre notre nouveau salon moderne. ✅ PROFIL RECHERCHÉ : - Minimum 2-3 ans d'expérience - Maîtrise des coupes modernes et tendances - Rapidité et qualité du travail- Bon contact avec la clientèle - Présentation soignée et professionnelle 💰 RÉMUNÉRATION ATTRACTIVE : - Salaire fixe + pourcentage (à discuter)  🎁 CE QUE NOUS OFFRONS   - Local moderne et bien équip  - Matériel professionnel fourn  - Excellent emplacement à Treichvill  - Ambiance de travail agréabl  - Possibilité d'évolutionDÉBUT : Immédiat ntéressé(e) ? Contactez-nous dès maintenant !  APPELEZ OU WHATSAPP :   Merci de contacter uniquement si vous habitez à proximité et si vous avez l'expérience requise #Recrutement #CoiffeurAbidjan #Treichville #Marcory #EmploiCotedIvoire #Barbier",
    location: "Abidjan",
    salary: "... FCFA",
    whatsapp: "2250596132058",
    number: "+2250708831002",
    likes: 12,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 4,
    zone: "Abidjan",
    category: "coiffeuse",
    title:
      "Recherche une coiffeuse et celle qui veulent se faire former dans le domaine de la coiffure",
    description:
      "Bonjour je recherche une coiffeuse et celle qui veulent se faire former dans le domaine de la coiffure nous sommes à bingerville précisément dans la zone de ENP",
    location: "bingerville",
    salary: "... FCFA",
    whatsapp: "2250596132058",
    number: "+2250594478116",
    likes: 102,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 5,
    zone: "Abidjan",
    category: "prothésiste",
    title: "Recherche prothésiste ongulaire  ",
    description:
      "Besoin d’une bonne prothésiste ongulaire à l’intérieur  whatsapp",
    location: "Abidjan",
    salary: "... FCFA",
    whatsapp: "2250596132058",
    number: "+2250506061014",
    likes: 102,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "19-Mai-2026",
  },
  {
    id: 6,
    zone: "Abidjan",
    category: "prothésiste",
    title: "Recherche prothésiste ongulaire  ",
    description:
      "J’ai besoin d’une coiffeuse qui maitrise bien les poses Et une prothésiste ongulaire qui maîtrise toutes les techniques, 90mil ",
    location: "Yopougon",
    salary: "90 000 FCFA",
    whatsapp: "2250596132058",
    number: "+2250778463356",
    likes: 102,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "09-Mai-2026",
  },

  {
    id: 7,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Salon recherche coiffeur propre",
    description:
      "Bonjour institut de beauté situé à la Riviera 2 recherche un coiffeur professionnel avec une bonne hygiène.",
    location: "La Riviera 2",
    salary: "Salaire à discuter",
    whatsapp: "2250596132058",
    number: "+2250140432710",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },

  {
    id: 8,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Salon gerance libre",
    description: "Salon en gerance libre à Bingerville.",
    location: "Bingerville",
    salary: "Salaire à discuter",
    whatsapp: "2250596132058",
    number: "+2250799651489",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },

  {
    id: 9,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Salon recherche coiffeuse polyvalente",
    description:
      "Salon situé à Cocody Angré 8ème tranche recherche une coiffeuse polyvalente.",
    location: "Cocody",
    salary: "80.000 - 120.000 FCFA",
    whatsapp: "2250596132058",
    number: "+225050470326",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 10,
    zone: "Abidjan",
    category: "Esthetique",
    title: "Esthéticienne recherche travail",
    description: "Recherche d'emploi pour prothésiste ongulaire à Port-Bouët.",
    location: "Port-Bouët",
    salary: "150.000 FCFA",
    whatsapp: "2250596132058",
    number: "+2250596560063",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },

  {
    id: 11,
    zone: "Abidjan",
    category: "Esthetique",
    title: "Recherche esthéticienne professionnelle",
    description: "Besoin d'une esthéticienne professionnelle à Cocody Mermoz.",
    location: "Cocody Mermoz",
    salary: "150.000 FCFA",
    whatsapp: "2250596132058",
    number: "+2250798996373",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },

  {
    id: 12,
    zone: "Intérieur",
    category: "Esthetique",
    title: "Recherche prothésiste ongulaire",
    description: "Recrutement d’un prothésiste ongulaire à Bouaké.",
    location: "Bouaké",
    salary: "",
    whatsapp: "2250596132058",
    number: "0554522544 / 0102239508",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  //

  {
    id: 13,
    zone: "Abidjan",
    category: "Formation",
    title: "Recherche apprenties",
    description:
      "Recherche de 3 apprenties en onglerie avec ou sans expérience.",
    location: "Bouaké",
    salary: "50.000 FCFA",
    whatsapp: "2250596132058",
    number: "+2250171793208",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },

  {
    id: 14,
    zone: "Abidjan",
    category: "Formation",
    title: "Coiffeur recherche formation",
    description:
      "Jeune passionné recherche formation en coiffure homme et dreadlocks.",
    location: "Yopougon",
    salary: "",
    whatsapp: "2250596132058",
    number: "+2250777533101",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },

  {
    id: 15,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Recherche coiffeur propre",
    description: "Gerance  sans  dortoire  salon de coiffure situé a adjame ",
    location: "Adjame",
    salary: "",
    whatsapp: "2250596132058",
    number: "+225 08 41 98 19",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "17-Mai-2026",
  },
  {
    id: 16,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Recherche coiffeur",
    description:
      "Gerance libre bouaké recherche coiffeur  barber dortoire disponible",
    location: "abidjan",
    salary: "",
    whatsapp: "2250596132058",
    number: "+2250757451711",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },
  {
    id: 17,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Recherche un coiffeur ",
    description:
      "Zone  Abidjan songon Categorie coiffure Titre. Recherche un coiffeur Le texte Salon de coiffure à Songon Agban cherche un coiffeur.Consciencieux, professionnel et respectueux. Avec DORTOIR Salaire a discuter ",
    location: "abidjan Agban",
    salary: "",
    whatsapp: "2250596132058",
    number: "+2250140470971",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },
  {
    id: 18,
    zone: "Abidjan",
    category: "Coiffeur",
    title: "Ala recherche d'une coiffeuse professionnelle",
    description:
      "Je  suis a la recherche d'une coiffeuse professionnelle pour rejoindre mon équipe à yopougon millionnaire critères recherchés:- courtoise, acceuillante &professionnelle  - maîtriser la pose perruque( lace,  frontal, closures) - les tresses tendances ( nattes braids)- les tissages - les soins de cheveux",
    location: "Yopougon",
    salary: "Admin",
    whatsapp: "2250596132058",
    number: "+225 0545000811",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 19,
    zone: "Intérieur",
    category: "Coiffeur",
    title: "Recherche un  coiffeur expérimenté ",
    description:
      "Urgent !!!Besoin d’un coiffeur expérimenté pour la gestion d’un salon de coiffure.Salaire de base de 40 000 fr  à 50 000 fr ou Gérance libre .Possibilité d’hébergement Lieu : Bouake précisément dans la localité de Tieningboue",
    location: "Tieningboue",
    salary: "40 000F  à 50 000F",
    whatsapp: "2250596132058",
    number: "0502211966 / 0757451711",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "18-Mai-2026",
  },

  //

  {
    id: 20,
    zone: "Abidjan",
    category: "Recherche travail",
    title: "A la recherche d'un travail ",
    description:
      "Je viens de finir ma formation d'onglerie je cherche un coin où faire un stage pour bien me perfectionner",
    location: "Abobo belle ville",
    salary: "40 000F  à 50 000F",
    whatsapp: "2250596132058",
    number: "+225 0769538828",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "16-Mai-2026",
  },
  {
    id: 21,
    zone: "Intérieur",
    category: "Esthéticien",
    title: "Recherche travail ",
    description:
      "Esthéticien homme sachant faire les ongles gel faux cil pose perruque recherche travail a bouaké ou ailleurs avec dortoire salaire ou gerance libre  de 150.000 a 250000",
    location: "Bouaké",
    salary: "150.000 Fcfa - 250000 Fcfa",
    whatsapp: "2250596132058",
    number: "+225 0586959610",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "02-Mai-2026",
  },
  {
    id: 21,
    zone: "Intérieur",
    category: "Coiffure",
    title: "Recherche coiffeur barber ",
    description:
      "Salon de coiffure situé a agboville recherche coiffeur barber. Salaire a discuter dortoire disponible",
    location: "Agboville",
    salary: "....",
    whatsapp: "2250596132058",
    number: "+225 0554115587",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "06-Mai-2026",
  },

  {
    id: 22,
    zone: "Intérieur",
    category: "Coiffeuse",
    title: "Recherche d'une coiffeuse professionnels ",
    description:
      "urgent 🚨je suis à la recherche d'une coiffeuse professionnels pour au solon VIP a bouaké 50000 dortoire disponible Posé peruq place faut ongles tresse gomage ect..",
    location: "bouaké",
    salary: "50 000 Fcfa",
    whatsapp: "2250596132058",
    number: "0152394723 ",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "09-Mai-2026",
  },

  {
    id: 23,
    zone: "Abidjan",
    category: "Prothésiste",
    title: "Offre de formation yopougon",
    description:
      "Tu as envie de devenir une prothésiste professionnelle Eden Éden institut beauty Est la pour toi Viens recevoir une formation en onglerie make-up et la pose perruque de qualité+un emploi garantie dans les Spa et institut Dans la commune de ton choix Éden institut te rend autonome par son programme de qualité si tu souhaites t'installer à ton propre compte ",
    location: "Yopougon",
    salary: "Voir admin",
    whatsapp: "2250596132058",
    number: " 0103036116 ",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "08-Mai-2026",
  },

  {
    id: 24,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Cherche travail salon de coiffure pour être apprenti",
    description:
      "Bonjour à tous je suis un jeune homme qui cherche salon de coiffure pour être apprenti. Je suis vraiment passionné par le métier, j'aimerais apprendre au près d'un coiffeur et travaillé avec lui par la suite",
    location: "Yopougon",
    salary: "...",
    whatsapp: "2250596132058",
    number: "0777533101 ",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 25,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche aide coiffeuse",
    description:
      "Bonjour besoin urgement d'une aide coiffeuse et d'une coiffeuse à cocody non loin de la RTI",
    location: "COcody",
    salary: "Voir admin",
    whatsapp: "2250596132058",
    number: "0103269672",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 26,
    zone: "Intérieur",
    category: "Cherche salon de coiffure pour travail avec dortoire",
    title: "Cherche  travail",
    description:
      "Coiffeur  barber resident a Yamoussokro. Recherche salon de coiffure pour travail avec dortoire. Salaire ou gerance libre",
    location: "Yamoussokro",
    salary: "Salaire ou gerance libre",
    whatsapp: "2250596132058",
    number: "+2250555432860",
    likes: 12,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 27,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Cherche  travail",
    description:
      "Coiffure homme et  locks Je suis Abidjan bingerville J'habite aussi à Gonzague",
    location: "bingerville Gonzague",
    salary: "...",
    whatsapp: "2250596132058",
    number: "+2250566569181",
    likes: 100,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },
  {
    id: 28,
    zone: "Intérieur",
    category: "Coiffure",
    title: "Recherche 3 coiffeur 3 barber a yakasse attobrou",
    description:
      "Recherche 3 coiffeur3 barber  a yakasse attobrou competence maitrise du dégrader taper contour dread teinture de couleur. Loyer disponible  salaite 50/50",
    location: "Abata",
    salary: "salaite 50/50",
    whatsapp: "2250596132058",
    number: "+225 0555027936",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "17-Mai-2026",
  },
  {
    id: 29,
    zone: "Abidjan",
    category: "Coiffeuses",
    title: "Ccherche travail",
    description: "Je suis une coiffeuses professionnel En tresses à  Abata",
    location: "Abata",
    salary: "150 000 FCFA",
    whatsapp: "2250596132058",
    number: "+225 0507890767",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },

  {
    id: 30,
    zone: "Abidjan",
    category: "Tresses",
    title: "Cherche travail",
    description:
      "Pas de dortoir, zone de prédilection Abobo belle ville, Abobo baoulé, abobo biabou, Paris village et Angré château limite.",
    location: "Abobo belle ville,",
    salary: "",
    whatsapp: "2250596132058",
    number: "+2250566569181",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "21-Mai-2026",
  },

  //

  {
    id: 31,
    zone: "Abidjan",
    category: "Coiffeuse",
    title: "recherche coiffeuse",
    description:
      "Abata Tout mèches,pose perruque, natte, pedicure.. Salaire  mille",
    location: "Abatta  ",
    salary: "100 000 FCFA",
    whatsapp: "2250596132058",
    number: "+2250757275034",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },
  {
    id: 32,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche une fille  pour soin  de visage, pas de dortoir",
    description:
      "J'ai besoin d'une fille pour faire pédicure manucure et soins de visage pas de dortoir. C'est un salon pour homme",
    location: "Treichville ",
    salary: "~ 80 000 FCFA",
    whatsapp: "2250596132058",
    number: "+225 0747939892:",
    likes: 304,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },

  {
    id: 33,
    zone: "Abidjan",
    category: "Coiffeuse",
    title: "Cherche travail ",
    description:
      "Coiffeuse polyvalente pose perruque .tresse natte tissage soins de visage manucure   resident a ABOBO DOKUI recherche emploi     dans les environs salaire ",
    location: "ABOBO DOKUI ",
    salary: "~ 130.000 FCFA",
    whatsapp: "2250596132058",
    number: "+225 0545488441",
    likes: 104,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },

  {
    id: 34,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Particulier Gestion LIBRE   Sans  DORTOIR.",
    description:
      "chercher un coiffeur spécialisé en coiffure Mixte où coiffure homme Dans la commune ABOBO anokoi",
    location: "ABOBO ",
    salary: "À débattre",
    whatsapp: "2250596132058",
    number: "+2250100341904",
    likes: 34,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },

  {
    id: 35,
    zone: "Intérieur",
    category: "Coiffure",
    title: "Recherche un Coiffeur.",
    description:
      "Besoins de COIFFEUR - SALAIRE VIP. VILLE DE KORHOGO Gestion LIBRE DORTOIR DISPONIBLE ",
    location: "KORHOGO ",
    salary: "À discuter",
    whatsapp: "2250596132058",
    likes: 34,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },

  {
    id: 36,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche Coiffeur",
    description:
      "Bonjour je cherche un coiffeur pour mon salon situé à gonzaque Pas de dortoir",
    location: "Abidjan ",
    salary: "À débattre",
    whatsapp: "2250596132058",
    likes: 12,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },

  {
    id: 37,
    zone: "Intérieur",
    category: "Esthéticienne",
    title: "Recherche une Esthéticienne",
    description:
      "Recherche une Esthéticienne polyvalente sur Bassam Qui maîtrise le soin de visage, gommage de corps, massage, pédicure manucure et onglerie. Salaire a discuter. NB pas de dortoire",
    location: "Bassam",
    salary: "À débattre",
    whatsapp: "2250596132058",
    number: "2250100134270",
    likes: 109,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,
    date: "20-Mai-2026",
  },

  {
    id: 38,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche un Coiffure ",
    description:
      "Besoin urgent de Coiffure assidu et patient qui habite a Yopougon Maroc ou aux alentours.",
    location: "Yopougon Maroc",
    salary: "À débattre",
    whatsapp: "2250596132058",
    number: "+22505 96 65 98 58",
    likes: 12,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: false,

    date: "14-Mai-2026",
  },

  {
    id: 39,
    zone: "Abidjan",
    category: "Prothésie",
    title: "Recherche Prothésiste Ongulaire",
    description:
      "Je cherche une prothésiste pour emploi immédiat au nouveau CHU.",
    location: "Angré CHU",
    salary: "À négocier",
    whatsapp: "2250700508392",
    number: "+22507 79 76 26 79",
    likes: 12,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    isDisponible: true,

    date: "05-Mai-2026",
  },

  {
    id: 40,
    zone: "Abidjan",
    category: "Esthétique",
    title: "Recherche Technicienne de Cils",
    description:
      "Recherche technicienne de cils urgent pour un salon de beauté.",
    location: "Cocody",
    salary: "À négocier",
    whatsapp: "2250799665342",
    number: "+22507 99 665 342",
    likes: 18,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    date: "20-Mai-2026",
  },

  {
    id: 41,
    zone: "Abidjan",
    category: "Prothésie",
    title: "Cherche travail",
    description:
      "Jeune dame polyvalente cherche un emploi. maîtrisant la prothésie ongulaire, les cils et les sourcils.",
    location: "Angré",
    salary: "À négocier",
    whatsapp: "2250777344290",
    number: "+2250777344290",
    likes: 25,
    isUrgent: false,
    isFavorite: true,
    hasDortoir: false,
    isPremium: false,
    date: "11-Mai-2026",
  },

  {
    id: 42,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche Coiffeuse et Aide Coiffeuse",
    description:
      "Recherche une coiffeuse et une aide coiffeuse maîtrisant les tresses et les nattes.",
    location: "Angré CHU",
    salary: "À négocier",
    whatsapp: "2250779762679",
    number: "+2250777344290",
    likes: 16,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    date: "20-Mai-2026",
  },

  {
    id: 43,
    zone: "Abidjan",
    category: "Recherche travail",
    title: "Coiffeur Professionnel  Recherche travail ",
    description: "Coiffeur professionnel recherche un salon avec dortoir.",
    location: "Port-Bouët / Grand-Bassam",
    salary: "À négocier",
    whatsapp: "2250507564428",
    number: "2250507564428",
    likes: 22,
    isUrgent: false,
    isFavorite: true,
    hasDortoir: true,
    isPremium: false,
    date: "21-Mai-2026",
  },

  {
    id: 44,
    zone: "Abidjan",
    category: "Vente / Coiffure",
    title: "Recherche Travail ",
    description:
      "Recherche du travail dans la vente en magasin ou dans un salon de coiffure.",
    location: "Abidjan",
    salary: "À négocier",
    whatsapp: "2250787321090",
    numer: "+2250787321090",
    likes: 14,
    isUrgent: false,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    date: "10-Mai-2026",
  },

  {
    id: 45,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche Coiffeuse et Coiffeur",
    description: "Recherche une coiffeuse et un coiffeur pour un salon.",
    location: "Yopougon Académie",
    salary: "À négocier",
    whatsapp: "2250142517776",
    number: "+2250142517776",
    likes: 20,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    date: "10-Mai-2026",
  },
  {
    id: 46,
    zone: "Abidjan",
    category: "Esthétique",
    title: "Recherche Pédicuriste & Capsules",
    description: "Spécialiste pose capsules et vernis permanent sur pieds.",
    location: "Angré 8ème tranche",
    salary: "90.000 FCFA",
    whatsapp: "2250596132058",
    number: "+22507 78 88 43 99",
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: false,
    date: "2024-05-03",
  },
  {
    id: 47,
    zone: "Abidjan",
    category: "prothésiste",
    title: "Recherche Multi-postes Faya Cité SIR",
    description:
      "#Besoin d'une apprenti qui sait faire pédicure et mettre les ongles et le vernis : 50mill  #Une prothésiste Ongulaire : 70k  #une coiffeuse ou un coiffeur professionnel : 80k #Lieu : Faya Cité SIR ",
    location: "Faya Cité SIR",
    salary: "50.000 - 80.000 FCFA",
    whatsapp: "2250596132058",
    number: "+2250101747343",
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: false,
    date: "2024-05-04",
  },

  {
    id: 48,
    zone: "Abidjan",
    category: "Coiffeuse",
    title: "Recherche Coiffeuse Perruques & Tresses",
    description:
      "J’ai besoin d’ une coiffeuse qui maitrise bien les poses perruques et tresses pour mon salon à yopougon 90mil ",
    location: "Yopougon",
    salary: "90.000 FCFA",
    whatsapp: "2250596132058",
    number: "+2250778463357",
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: false,
    date: "2024-05-05",
  },

  {
    id: 49,
    zone: "Abidjan",
    category: "Coiffure/Coiffeuse",
    title: "Coiffeur(se) Professionnel(le) Perruques",
    description:
      "Besoin urgent d'une coiffeuse ou d'un coiffeur professionnel maîtrisant les poses de perruques.",
    location: "Bingerville",
    salary: "150.000 FCFA",
    whatsapp: "2250710752338",
    number: "+2250710752338",
    likes: 47,
    isUrgent: true,
    isFavorite: true,
    hasDortoir: false,
    isPremium: true,
    date: "10-Mai-2026",
  },

    {
    id: 50,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche Coiffeur ",
    description:
      "Coiffeur professionnel disponible cherche un barber avec possibilité de dortoir.",
    location: "Abidjan",
    salary: "À négocier",
    whatsapp: "2250505800053",
    number: "+2250505800053",
    likes: 28,
    isUrgent: false,
    isFavorite: false,
    hasDortoir: true,
    isPremium: false,
    date: "10-Mai-2026",
  },

  {
    id: 51,
    zone: "Abidjan",
    category: "Coiffeuse",
    title: "Coiffeuse Recherche Travail avec Logement",
    description:
      "Je suis une coiffeuse et je recherche du travail dans un salon avec logement.",
    location: "Abidjan",
    salary: "À négocier",
    whatsapp: "2250150962273",
    number: "+2250150962273",
    likes: 19,
    isUrgent: false,
    isFavorite: true,
    hasDortoir: true,
    isPremium: false,
    date: "10-Mai-2026",
  },

   {
    id: 52,
    zone: "Abidjan",
    category: "Prothésie",
    title: "Cherche travail",
    description:
      "Prothésiste en fin de formation disponible uniquement dans la zone de Angré.",
    location: "Angré",
    salary: "À négocier",
    whatsapp: "2250715416616",
    number: "+2250715416616 ",
    likes: 15,
    isUrgent: false,
    isFavorite: false,
    hasDortoir: false,
    isPremium: false,
    date: "10-Mai-2026",
  },

  {
    id: 53,
    zone: "Abidjan",
    category: "Coiffure",
    title: "Recherche Coiffeuse et Prothésiste Ongulaire",
    description:
      "Recherche une coiffeuse et une prothésiste ongulaire pour un salon sérieux.",
    location: "Yopougon Maroc",
    salary: "À négocier",
    whatsapp: "2250779161504",
    likes: 31,
    isUrgent: true,
    isFavorite: false,
    hasDortoir: false,
    isPremium: true,
    date: "10-Mai-2026",
  },

  { 
    id: 54, 
    zone: "Intérieur", 
    category: "Coiffeuse", 
    title: "Coiffeuse à Bassam", 
    description: "Besoin d'une coiffeuse à Bassam avec dortoir disponible immédiatement. Salaire : 60.000f Heure : 9h a 20h 30 ", 
    location: "Grand-Bassam", 
    salary: "60.000 FCFA",
    whatsapp: "2250596132058", 
    number: "+22505 44 63 91 54", 
    likes: 28,
    isUrgent: false,
    isFavorite: true,
    hasDortoir: true,
    isPremium: false,
    date: "2024-05-14"
  },
   { 
    id: 55, 
    zone: "Abidjan", 
    category: "Esthétique", 
    title: "Recherche Expert Spa & Extensions", 
    description: "Soins corps/visage et extensions de cils (Russe/Hybride).", 
    location: "Riviera Mbadon", 
    salary: "200.000 - 250.000 FCFA",
    whatsapp: "2250596132058", 
    number: "22507 67 95 55 55", 
    likes: 105, // Mis à jour à au moins 12
    isUrgent: false,
    isFavorite: true, 
    hasDortoir: false,
    isPremium: true,
    date: "19-Mai-2026"
  },

   
  { 
    id: 56, 
    zone: "Abidjan", 
    category: "Coiffure", 
    title: "Recherche Coiffeuse experte en poses", 
    description: "Besoin d'une coiffeuse à abatta qui maîtrise surtout les pose perruque. Heure : 9h a 20h 30.", 
    location: "Abatta", 
    salary: "70.000 FCFA",
    whatsapp: "2250596132058", 
    number: "+22505 44 63 91 54", 
    likes: 12,
    isUrgent: false,
    hasDortoir: false,
        isFavorite: true, 

    isPremium: false,
    date: "2024-05-13"
  },

  { 
    id: 57, 
    zone: "Abidjan", 
    category: "Esthétique", 
    title: "Recherche Prothésiste Ongulaire Pro", 
    description: "besoin de deux prothésiste ongulaire urgemment dans la zone d’abobo baoulé, salaire de départ 70k à négocier", 
    location: "Abobo Baoulé", 
    salary: "70.000 FCFA",
    whatsapp: "2250596132058", 
    number: "+2250153488797", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: false,
    date: "2024-05-06"
  },
  { 
    id: 58, 
    zone: "Abidjan", 
    category: "Esthétique", 
    title: "Expert Spa & Extensions", 
    description: "Soins corps/visage et extensions de cils (Russe/Hybride).", 
    location: "Riviera Mbadon", 
    salary: "200.000 - 250.000 FCFA",
    whatsapp: "2250596132058", 
    number: "+22507 67 95 55 55 ", 
    likes: 0,
    isUrgent: false,
    hasDortoir: false,
    isPremium: true,
    date: "19-Mai-2026"
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Awa Koné",
    role: "Coiffeuse Professionnelle",
    content: "Grâce à Goorco, j'ai trouvé un salon à Angré en moins de 48h. Le contact via WhatsApp est ultra rapide !",
    rating: 5,
    avatar: "/esthe1.jpeg"
  },
  {
    id: 2,
    name: "Marc Koffi",
    role: "Gérant de Salon",
    content: "Recruter du personnel qualifié était un calvaire. Avec cette plateforme, j'ai accès aux meilleurs profils de la ville.",
    rating: 5,
    avatar: "/esth2.jpg"
  },
  {
    id: 3,
    name: "Sery Dorcas",
    role: "Esthéticienne",
    content: "La section 'Dortoir disponible' m'a vraiment aidée car je venais de l'intérieur du pays. Je recommande !",
    rating: 4,
    avatar: "/esth3.jpg"
  },

];





